on: 
  workflow_dispatch:
    inputs:
      environment:
        type: options
        description: 'Define env name'     
        required: true
        default: 'dev1'
        options:
          - dev1
          - dev2
          - dev3
      branch:
        description: 'Define Front End Branch Name'     
        required: true
        default: 'master'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.environment }}" 
        echo "Branch: ${{ github.event.inputs.branch }}"
